[package]
name = "mq"
version = "0.0.1"

# mq compiles to a NATIVE binary via the C backend (mere -c | clang) —
# no Node host, unlike the mere-notes web app. So no [host] section.
[dependencies]
json = { git = "https://github.com/merelang/mere", subdir = "contrib/json", rev = "39ae7b91121899f2c6cb752f884d52aaca46bc83" }
csv  = { git = "https://github.com/merelang/mere", subdir = "contrib/csv",  rev = "39ae7b91121899f2c6cb752f884d52aaca46bc83" }
